name: Deploy API Mock

on:
  push:
    branches:
      - '**'  # Isso vai acionar o workflow para qualquer branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # ou a versão que você estiver usando

      - name: Install dependencies
        run: npm install

      - name: Deploy to Render
        env:
          BRANCH_NAME: "${GITHUB_REF_NAME}"  # Definindo BRANCH_NAME
        run: |
          curl -X POST https://api.onrender.com/deploys \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"serviceId": "${{ secrets.RENDER_SERVICE_ID }}", "branch": "${GITHUB_REF_NAME}"}'
